language: python

python:
  - "2.7.12"
  - "3.5.2"

install:
  - pip install -r requirements.txt

script:
  - nosetests --exe -v
  - nosetests --exe --with-coverage
  - coveralls
  - py.test

after_success:
- "coveralls"