language: python

python:
  - "2.7.12"
  - "3.5.2"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE ride;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'python';"
  - psql -c "GRANT ALL PRIVILEGES ON database ride TO postgres;"

script:
  - "coveralls"
  - py.test

after_success:
- "coveralls"
