language: python

python:
  - "2.7.12"
  - "3.5.2"

install:
  - pip install -r requirements.txt

script:
  nosetests  --with-coverage --cover-package=ridemyway && coveralls

after_success:
- "coveralls"