language: python

python:
  - "3.5.2"

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

env:
  - DB = postgres USER = postgres PASSWORD = 'python'

before_script:
  - psql -c "CREATE DATABASE ride;" -U postgres

script:
  - nosetests  --with-coverage --cover-package=app && coveralls
   - pytest

after_success:
- "coveralls"
