language: python

python:
  - "2.7.12"
  - "3.5.2"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database ride'
  - cp database.yml.travis config/database.yml

script:
  - "coveralls"
  - py.test

after_success:
- "coveralls"
