language: python

python:
  - "2.7.12"
  - "3.5.2"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "create database ride;" -U postgres
  - psql -c "create user postgres with password 'python';"
  - psql -c "grant all privillage on database ride to postgres;"

script:
  - "coveralls"
  - py.test

after_success:
- "coveralls"
