language: python

python:
  - "2.7.12"
  - "3.5.2"

services:
  - postgres

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "create database ride;"
  - psql -c "create user danti with password 'python';"
  - psql -c  "grant all privileges on database ride to danti;"
  - cp database.yml.travis config/database.yml

script:
  - "coveralls"
  - py.test

after_success:
- "coveralls"
